# Configure the PHP version SensioLabsInsight should use to analyze
# your project. It can be defined to 5, 7.0, or 7.1. If not
# present, it will prefer 7.1 but fallback to 5 if errored.
php_version: 5


# This section will be executed before installing dependencies.
# You should configure here what is needed for Composer to run without
# issue: install libraries, prepare the database, etc.
pre_composer_script: |
    #!/bin/bash
    cp app/config/parameters.yml.dist app/config/parameters.yml
    sed -i -e "s/assets_version:.*/assets_version: `date +'%s'`" app/config/parameters.yml