<?php

namespace AppBundle\Repository;

/**
 * CartoucheRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartoucheRepository extends \Doctrine\ORM\EntityRepository
{
}
