<?php

namespace AppBundle\Repository;

/**
 * ImprimanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImprimanteRepository extends \Doctrine\ORM\EntityRepository
{
	public function numberPrinters()
	{
		 return (int) $this
		    ->createQueryBuilder('a')
		    ->select('COUNT(a.id)')
		    ->getQuery()
		    ->getSingleScalarResult()
		 ;
	}
}
